ktor:
  deployment:
    port: 8080
    rootPath: '/api'

# 服务端地址, 该项决定了API文档中的请求地址
serverUrl:
  - 'https://sub.subit.org.cn'

# 服务器host, 该项决定了CORS策略中的允许请求地址
# 允许使用通配符例如*.subit.org.cn
serverHost:
  - '*.subit.org.cn'
database:
  # 数据库实现, 可选值: sql, memory
  impl: sql
  sql: # 该配置项仅在 impl 为 sql 时必须, 其余情况下无效

    # 支持的数据库：
    # - Postgres

    #数据库用户名
    user: 'YourSqlUser'
    #数据库密码
    password: 'YourSqlPassword'

    # 数据库连接地址
    url: 'jdbc:postgresql://YourSqlHost:YourSqlPort/YourDatabaseName' # postgres

    # 数据库驱动 该项可以不填或填为null以通过url自动识别对应驱动
    driver: null
    ## driver: 'com.impossibl.postgres.jdbc.PGDriver' # postgres

    # 数据库懒惰初始化
    lazyInit: true

# jwt登陆验证
#jwt:
#  secret: "SUBIT_SECRET" # Your can set your own secret key here, or a random one will be used